name: Rodar script Python automaticamente

on:
  schedule:
    - cron: '0 8-18 * * 1-5'  # De hora em hora, das 8h às 18h (segunda a sexta)
  workflow_dispatch:         # Permite executar manualmente também

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar script
        run: python teste.py
