name: Run Python script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8-18 * * 1-5'  # Executa de hora em hora, seg a sex

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: List files in directory
        run: |
          echo "Listando arquivos no diretório:"
          ls -la  # Exibe o conteúdo do diretório onde o script será executado

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python teste.py
